DROP SEQUENCE HIBERNATE_SEQUENCE;

DROP TABLE KUNDE CASCADE CONSTRAINTS PURGE;
DROP TABLE ROLLE CASCADE CONSTRAINTS PURGE;
DROP TABLE KUNDE_ROLLE CASCADE CONSTRAINTS PURGE;
DROP TABLE ADRESSE CASCADE CONSTRAINTS PURGE;
DROP TABLE BESTELLUNG CASCADE CONSTRAINTS PURGE;
DROP TABLE PRODUKT CASCADE CONSTRAINTS PURGE;
DROP TABLE BESTELLPOSITION CASCADE CONSTRAINTS PURGE;
